import { Post } from '@/types'

// Datos de ejemplo para ver el diseño sin base de datos
export const mockPosts: Post[] = [
  {
    id: '1',
    content: 'Un fin de semana increíble en el retiro espiritual. Estas imágenes capturan momentos que nunca olvidaré. 🧘‍♀️ ✨',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1985-03-15'),
    updatedAt: new Date(),
    authorId: '1',
    author: {
      id: '1',
      email: 'maria@example.com',
      name: 'María López',
      username: 'marialopez',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 1234,
      comments: 234,
    },
  },
  {
    id: '2',
    content: 'Bendecido por poder compartir este mensaje con todos ustedes. La palabra de Dios nos fortalece cada día. 🙏',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1987-06-20'),
    updatedAt: new Date(),
    authorId: '2',
    author: {
      id: '2',
      email: 'ana@example.com',
      name: 'Ana García',
      username: 'anagarcia',
      image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: false,
    },
    _count: {
      likes: 567,
      comments: 89,
    },
  },
  {
    id: '3',
    content: 'Testimonio de fe: Dios obra de formas maravillosas en nuestras vidas. 💙',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1982-11-10'),
    updatedAt: new Date(),
    authorId: '3',
    author: {
      id: '3',
      email: 'carlos@example.com',
      name: 'Carlos Martínez',
      username: 'carlosmartinez',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 890,
      comments: 156,
    },
  },
  {
    id: '4',
    content: 'Queridos hermanos y hermanas en Cristo, hoy quiero compartir con ustedes un testimonio muy especial que ha marcado mi vida de manera profunda. Hace algunos meses, estaba pasando por un momento muy difícil en mi vida personal y profesional. Sentía que todo se derrumbaba a mi alrededor y no sabía cómo seguir adelante. Fue entonces cuando decidí entregar completamente mi situación a Dios, confiando en que Él tenía un plan perfecto para mí. Comencé a orar intensamente y a leer Su palabra cada día, buscando dirección y paz en medio de la tormenta. Poco a poco, empecé a ver cómo Dios obraba de maneras que nunca hubiera imaginado. Las puertas que parecían cerradas comenzaron a abrirse, y las situaciones que parecían imposibles empezaron a resolverse. Hoy puedo decir con certeza que Dios es fiel y que Su tiempo es perfecto. Este retiro espiritual que comparto en estas imágenes fue un momento clave en mi proceso de sanación y renovación. 🙏✨',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1988-09-05'),
    updatedAt: new Date(),
    authorId: '4',
    author: {
      id: '4',
      email: 'david@example.com',
      name: 'David Rodríguez',
      username: 'davidrodriguez',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: false,
    },
    _count: {
      likes: 2345,
      comments: 456,
    },
  },
  {
    id: '5',
    content: 'Hermanos y hermanas, quiero compartir con ustedes una reflexión que ha estado en mi corazón durante estos últimos días. La vida cristiana no es un camino fácil, pero es el camino más hermoso que podemos recorrer. Cada día nos presenta desafíos, pero también nos presenta oportunidades para crecer en nuestra fe y confiar más en nuestro Padre celestial. Cuando miro hacia atrás y veo todo lo que Dios ha hecho en mi vida, me lleno de gratitud y asombro. Él ha sido mi refugio en tiempos de tormenta, mi luz en momentos de oscuridad, y mi fuerza cuando me sentía débil. La palabra de Dios dice en Jeremías 29:11: "Porque yo sé los planes que tengo para ustedes", declara el Señor, "planes de bienestar y no de calamidad, para darles un futuro y una esperanza". Esta promesa ha sido mi ancla en los momentos más difíciles. Quiero animarlos a que no se rindan, a que sigan confiando en Dios aunque las circunstancias parezcan adversas. Él está trabajando en nuestras vidas de maneras que no siempre podemos ver o entender, pero Su plan es perfecto. Oren sin cesar, lean Su palabra diariamente, y manténganse firmes en la fe. Dios los bendiga a todos. 🙏💙',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1983-04-22'),
    updatedAt: new Date(),
    authorId: '5',
    author: {
      id: '5',
      email: 'laura@example.com',
      name: 'Laura Sánchez',
      username: 'laurasanchez',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 1890,
      comments: 312,
    },
  },
  {
    id: '6',
    content: 'Hermanos y hermanas, necesito sus oraciones. Mi mamá está pasando por un momento de salud muy difícil y mi familia necesita la fuerza y la paz de Dios. Sé que Él es poderoso para sanar y restaurar. Agradezco cada oración de intercesión. Dios los bendiga. 🙏',
    postType: 'prayer',
    intercessionsCount: 347,
    isAnswered: false,
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1980-12-08'),
    updatedAt: new Date(),
    authorId: '6',
    author: {
      id: '6',
      email: 'juan@example.com',
      name: 'Juan Pérez',
      username: 'juanperez',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 567,
      comments: 89,
    },
  },
  {
    id: '7',
    content: 'Querida familia en Cristo, les pido sus oraciones urgentes. Mi esposo perdió su trabajo hace dos semanas y estamos pasando por una situación económica muy difícil. Confiamos en que Dios proveerá, pero necesitamos la intercesión de la comunidad. Oren por sabiduría, provisiones y paz en medio de esta prueba. Sé que nuestro Padre es fiel y tiene un plan perfecto. Gracias por estar con nosotros en oración. 🙏💙',
    postType: 'prayer',
    intercessionsCount: 128,
    isAnswered: false,
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1986-07-14'),
    updatedAt: new Date(),
    authorId: '7',
    author: {
      id: '7',
      email: 'patricia@example.com',
      name: 'Patricia Fernández',
      username: 'patriciaf',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: false,
    },
    _count: {
      likes: 234,
      comments: 45,
    },
  },
  {
    id: '8',
    content: 'Hermanos, necesito sus oraciones por mi hijo adolescente. Está pasando por una crisis de fe y se ha alejado de Dios. Como madre, mi corazón está quebrantado. Sé que la oración de los justos puede mucho, y confío en que Dios tocará su corazón. Oren para que el Espíritu Santo lo guíe de vuelta al camino. Oren también por mi familia, para que tengamos paciencia y sabiduría para amarlo como Cristo nos ama. Gracias por interceder. 🙏✨',
    postType: 'prayer',
    intercessionsCount: 89,
    isAnswered: false,
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
    ],
    createdAt: new Date('1990-02-28'),
    updatedAt: new Date(),
    authorId: '8',
    author: {
      id: '8',
      email: 'marta@example.com',
      name: 'Marta González',
      username: 'martagonzalez',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 156,
      comments: 32,
    },
  },
  {
    id: '9',
    content: 'Compartiendo momentos del culto de ayer. La alabanza y la predicación tocaron muchos corazones. Gracias a todos los que se sumaron. 🙏✨',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    authorId: '1',
    author: {
      id: '1',
      email: 'maria@example.com',
      name: 'María López',
      username: 'marialopez',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 432,
      comments: 67,
    },
  },
  {
    id: '10',
    content: 'Retiro de jóvenes en la montaña. Adoración, enseñanza y mucha comunión. Dios se movió de manera poderosa. 📷',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=800&fit=crop',
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    authorId: '2',
    author: {
      id: '2',
      email: 'ana@example.com',
      name: 'Ana García',
      username: 'anagarcia',
      image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: false,
    },
    _count: {
      likes: 289,
      comments: 41,
    },
  },
  {
    id: '11',
    content: 'Noche de alabanza en la iglesia. Estos videos son solo un pedacito de lo que vivimos. Dios es bueno. 🎵💙',
    mediaUrl: null,
    mediaType: null,
    mediaUrls: [
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=800&fit=crop',
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    authorId: '3',
    author: {
      id: '3',
      email: 'carlos@example.com',
      name: 'Carlos Martínez',
      username: 'carlosmartinez',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
      bio: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      isOnline: true,
    },
    _count: {
      likes: 512,
      comments: 78,
    },
  },
]

